export const raw_data = [
  {name: "Straight Outta Compton", grade: "5.12d", date: null, ascent_type: null},
  {name: "Jesus Wept", grade: "5.12d", date: null, ascent_type: null},
  {name: "Space Lord", grade: "5.12c", date: null, ascent_type: null},
  {name: "Heart Shaped Box", grade: "5.12c", date: null, ascent_type: null},
  {name: "Belly of the Beast", grade: "5.12c", date: null, ascent_type: null},
  {name: "Cell Block Six", grade: "5.12c", date: null, ascent_type: null},
  {name: "Mosaic", grade: "5.12c", date: null, ascent_type: null},
  {name: "Sliding Down Across A Million Years", grade: "5.12b", date: null, ascent_type: null},
  {name: "Batarang", grade: "5.12b", date: null, ascent_type: null},
  {name: "Charro", grade: "5.12b", date: null, ascent_type: null},
  {name: "Bullet the New Sky", grade: "5.12b", date: null, ascent_type: null},
  {name: "Babyface", grade: "5.12b", date: null, ascent_type: null},
  {name: "Far From God", grade: "5.12b", date: null, ascent_type: null},
  {name: "Bullfighter", grade: "5.12b", date: null, ascent_type: null},
  {name: "This is the City", grade: "5.12a", date: null, ascent_type: null},
  {name: "Where Egos Dare", grade: "5.12a", date: null, ascent_type: null},
  {name: "Honey Bucket", grade: "5.12a", date: null, ascent_type: null},
  {name: "49", grade: "5.12a", date: null, ascent_type: null},
  {name: "Hot Tamale Baby", grade: "5.12a", date: null, ascent_type: null},
  {name: "Twinkie", grade: "5.12a", date: null, ascent_type: null},
  {name: "Starry", grade: "5.12a", date: null, ascent_type: null},
  {name: "Scneezal", grade: "5.12a", date: null, ascent_type: null},
  {name: "Crumblies", grade: "5.12a", date: null, ascent_type: null},
  {name: "Posse Whipped", grade: "5.12a", date: null, ascent_type: null}
]